//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviation_events
    {
        public int id { get; set; }
        public int batch_id { get; set; }
        public Nullable<int> step_id { get; set; }
        public string deviation_type { get; set; }
        public string description { get; set; }
        public string severity { get; set; }
        public Nullable<bool> resolved { get; set; }
        public Nullable<System.DateTime> resolved_at { get; set; }
        public Nullable<int> resolved_by { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual batch_steps batch_steps { get; set; }
        public virtual batches batches { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
