//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quality_tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quality_tests()
        {
            this.test_results = new HashSet<test_results>();
        }
    
        public int id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> material_id { get; set; }
        public Nullable<System.DateTime> analysis_date { get; set; }
        public string sample_type { get; set; }
        public string status { get; set; }
        public string decision { get; set; }
        public string analyst_comment { get; set; }
        public Nullable<int> analyst_id { get; set; }
    
        public virtual batches batches { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_results> test_results { get; set; }
    }
}
