//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tech_cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tech_cards()
        {
            this.tech_card_steps = new HashSet<tech_card_steps>();
        }
    
        public int id { get; set; }
        public int product_id { get; set; }
        public int version { get; set; }
        public string status { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> approved_by { get; set; }
        public Nullable<System.DateTime> approved_at { get; set; }
        public string description { get; set; }
    
        public virtual products products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tech_card_steps> tech_card_steps { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
