//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_steps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batch_steps()
        {
            this.deviation_events = new HashSet<deviation_events>();
        }
    
        public int id { get; set; }
        public int batch_id { get; set; }
        public int step_id { get; set; }
        public int step_order { get; set; }
        public string step_name { get; set; }
        public Nullable<decimal> actual_temp_c { get; set; }
        public Nullable<int> actual_duration_min { get; set; }
        public Nullable<decimal> actual_pressure_bar { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<bool> deviation_flag { get; set; }
        public string operator_comment { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual batches batches { get; set; }
        public virtual tech_card_steps tech_card_steps { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deviation_events> deviation_events { get; set; }
    }
}
