//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_materials
    {
        public int id { get; set; }
        public int batch_id { get; set; }
        public int material_id { get; set; }
        public string lot_number { get; set; }
        public decimal quantity_used_kg { get; set; }
        public string supplier_lot { get; set; }
    
        public virtual batches batches { get; set; }
        public virtual materials materials { get; set; }
    }
}
