//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batches()
        {
            this.batch_materials = new HashSet<batch_materials>();
            this.batch_steps = new HashSet<batch_steps>();
            this.deviation_events = new HashSet<deviation_events>();
            this.quality_tests = new HashSet<quality_tests>();
        }
    
        public int id { get; set; }
        public string batch_number { get; set; }
        public int order_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string status { get; set; }
        public Nullable<decimal> actual_quantity_kg { get; set; }
        public Nullable<int> current_step_id { get; set; }
        public Nullable<int> deviation_count { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_materials> batch_materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_steps> batch_steps { get; set; }
        public virtual production_orders production_orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deviation_events> deviation_events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quality_tests> quality_tests { get; set; }
    }
}
