//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string line { get; set; }
        public string equipment_type { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
