//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgroControlEntities : DbContext
    {
        public AgroControlEntities()
            : base("name=AgroControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch_materials> batch_materials { get; set; }
        public virtual DbSet<batch_steps> batch_steps { get; set; }
        public virtual DbSet<batches> batches { get; set; }
        public virtual DbSet<deviation_events> deviation_events { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<production_orders> production_orders { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<quality_tests> quality_tests { get; set; }
        public virtual DbSet<recipe_components> recipe_components { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
        public virtual DbSet<statuses> statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tech_card_steps> tech_card_steps { get; set; }
        public virtual DbSet<tech_cards> tech_cards { get; set; }
        public virtual DbSet<test_results> test_results { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
