//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_work2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class statuses
    {
        public int id { get; set; }
        public string entity_type { get; set; }
        public string status_name { get; set; }
        public string status_code { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
